/**
 * ThoughtFarmer FormFlow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as models from './models';
export interface ApiFormSection {
    sectionId?: number;
    sortOrder?: number;
    label?: Array<models.StringStringKeyValuePair>;
    fields?: Array<models.ApiFormField>;
    isDeleted?: boolean;
    canEdit?: boolean;
}
