/**
 * ThoughtFarmer FormFlow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as models from './models';
export interface ApiForm {
    formId?: number;
    isLaunched?: boolean;
    isArchived?: boolean;
    title?: Array<models.StringStringKeyValuePair>;
    description?: Array<models.StringStringKeyValuePair>;
    thankyouTitle?: Array<models.StringStringKeyValuePair>;
    thankyouMessage?: Array<models.StringStringKeyValuePair>;
    closedTitle?: Array<models.StringStringKeyValuePair>;
    closedMessage?: Array<models.StringStringKeyValuePair>;
    noPermissionsTitle?: Array<models.StringStringKeyValuePair>;
    noPermissionsMessage?: Array<models.StringStringKeyValuePair>;
    startButtonLabel?: Array<models.StringStringKeyValuePair>;
    submitButtonLabel?: Array<models.StringStringKeyValuePair>;
    entryTitleTemplate?: Array<models.StringStringKeyValuePair>;
    sections?: Array<models.ApiFormSection>;
    createdDate?: string;
    modifiedDate?: string;
    launchDate?: string;
    closedDate?: string;
    deletedDate?: string;
    creatorId?: number;
    ownerId?: number;
    modifiedById?: number;
    totalSubmissionLimit?: number;
    userSubmissionLimit?: number;
    statuses?: Array<models.ApiFormStatus>;
    /**
     * True if the current user has permissions to submit an entry for the current form. NOTE: They may not be able to submit if maximum submission limits have been reached. Check the flag SubmissioinLimitExceeded.
     */
    userCanSubmit?: boolean;
    /**
     * True if the total submission limit, or the limit for the current user has been exceeded. When true any attempt to submit an entry by this user will produce an error response.
     */
    submissionLimitExceeded?: boolean;
}
