/**
 * ThoughtFarmer FormFlow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as models from './models';
export interface ApiFormFieldOption {
    optionId?: number;
    sortOrder?: number;
    value?: string;
    label?: Array<models.StringStringKeyValuePair>;
    logicAction?: models.FormLogicAction;
    logicTargetId?: number;
    isDeleted?: boolean;
}
