/**
 * ThoughtFarmer FormFlow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export interface ApiFormEntry {
    entryId?: number;
    entryNumber?: number;
    formId?: number;
    submitterId?: number;
    assigneeId?: number;
    startDate?: string;
    submittedDate?: string;
    deletedDate?: string;
    dueDate?: string;
    status?: number;
    statusLabel?: string;
    data?: string;
    isDeleted?: boolean;
    isArchived?: boolean;
    isOverdue?: boolean;
    canEdit?: boolean;
    canUpdateFields?: boolean;
    canComment?: boolean;
    canViewActivity?: boolean;
    /**
     * Reviewers of a form may be assigned any form entry for that form. These reviewers have been set on the form level and cannot be removed.
     */
    reviewers?: Array<number>;
    /**
     * Adhoc reviewers have been set on the form entry level and can be removed.
     */
    adhocReviewers?: Array<number>;
}
