/**
 * ThoughtFarmer FormFlow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export interface ApiUser {
    userId?: number;
    contentId?: number;
    fullName?: string;
    url?: string;
    imageUrl?: string;
    isAdministrator?: boolean;
    allowedInAdminMode?: boolean;
    isActive?: boolean;
    isDeleted?: boolean;
    canCreateForms?: boolean;
    culture?: string;
    managerId?: number;
    securityGroups?: Array<number>;
    directReports?: Array<number>;
    hideArchivedContent?: boolean;
    timeZoneId?: string;
}
