/**
 * ThoughtFarmer FormFlow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *     0 = None    1 = ShowField    2 = HideField    3 = ShowSection    4 = HideSection
 */
/**
*     0 = None    1 = ShowField    2 = HideField    3 = ShowSection    4 = HideSection
*/
export declare enum FormLogicAction {
    NUMBER_0,
    NUMBER_1,
    NUMBER_2,
    NUMBER_3,
    NUMBER_4
}
