import { ITag } from '../content/ITag';
import { PageType } from '../content/PageType';
import { ILikingModel } from './ILikingModel';
import { LinkType } from '../LinkType';

export interface INewsFeedItem {
    contentId?: number;
    link?: string;
    title?: string;
    summary?: string;
    body?: string;
    datePublished?: Date;
    datePublishedIso8601?: string;
    publishedByUserUrl?: string;
    publishedByUserName?: string;
    publishedByUserId?: number;
    publishedByUserImage?: string;
    showSummary?: boolean;
    disabled?: boolean;
    disabledLabel?: string;
    isEvent?: boolean;
    eventDate?: string;
    eventRepeatDetail?: string;
    isImportant?: boolean;
    isPrivate?: boolean;
    itemCssClass?: string;
    itemType?: string;
    isFuture?: boolean;
    isArchived?: boolean;
    isNew?: boolean;
    isUpdated?: boolean;
    culture?: string;
    image?: string;
    carouselImageLarge?: string;
    commentUrl?: string;
    commentLabel?: string;
    commentCount?: number;
    parentUrl?: string;
    parentTitle?: string;
    linkClass?: string;
    allowsComments?: boolean;
    allowsLikes?: boolean;
    liking?: ILikingModel;
    newsListImage?: string;
    pageType?: PageType;
    isLink?: boolean;
    editUrl?: string;
    linkTarget?: string;
    linkType?: LinkType;
    externalImageUrl?: string;
    viaLinks?: string[];
    generatedSummary?: string;
    generatedSimpleSummary?: string;
    hasBody?: boolean;
    isMailingListPost?: boolean;
    parentContentId?: number;
    grandParentContentId?: number;
    tags?: ITag[];
}