/**
 * ThoughtFarmer FormFlow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/// <reference types="jquery" />
import * as models from '../model/models';
import { Configuration } from '../configuration';
export declare class ApiUserApi {
    protected basePath: string;
    defaultHeaders: Array<string>;
    defaultExtraJQueryAjaxSettings?: JQueryAjaxSettings;
    configuration: Configuration;
    constructor(basePath?: string, configuration?: Configuration, defaultExtraJQueryAjaxSettings?: JQueryAjaxSettings);
    private extendObj;
    /**
     * **NOTE:** Requires the Authorization header to be sent with the REST API token.   Unless the request is coming from ThougthFarmer directly, then it will use the currently logged in users identity automatically.
     * @summary Gets a user from the main ThoughtFarmer Application
     */
    publicUserCurrentGet(extraJQueryAjaxSettings?: JQueryAjaxSettings): JQuery.Promise<{
        response: JQueryXHR;
        body: models.ApiUser;
    }, {
        response: JQueryXHR;
        errorThrown: string;
    }>;
}
