export enum SortType {
    DateCreated = 0,
    DateModified = 1,
    DatePublished = 2,
    LastName = 3,
    Relevance = 4,
    Title = 5,
    IsImportant = 6,
    TreePath = 7,
    LastActiveDate = 8,
    FirstName = 9,
    Popularity = 10,
    OwnerName = 11,
    Votes = 12,
    PageType = 13,
    Mentioned = 14,
    Label = 15,
    Usage = 16,
    BundleOrCustomField = 17,
    ExternalUserStoreGroupName = 18,
}